### ISSUE TITLE
Добавить всплывающие описания

### ISSUE THREAD

**Issue by simgislab** [nextgis/d-day#3]
подчеркнуть одну из тем голубым пунктиром и добавить небольшой текст описание всплывающий по нажатию.

Например для первой темы:

"За этот год NextGIS прошел большой путь и мы наконец смогли реализовать несколько своих давних задумок. В основном для нас это означает открытие нового направления сервисов, которое мы надеемся станет одним из основных."

Можно ли использовать в таких штуках html? Тогда в идеале было бы круто справа или слева от текста дать фоточку докладчика.

**Comment by lisovenkoNastya** [comment]
Сделала [https://github.com/nextgis/d-day/commit/6a4aa74cf105cec0ba22246a5a96af22b88ac783](https://github.com/nextgis/d-day/commit/6a4aa74cf105cec0ba22246a5a96af22b88ac783)
